add_time:
  name: Add Time
  description: Add an hour to the automatic shutoff timer of the WHF.
  fields:
    entity_id:
      name: Entity ID
      description: Entity ID of the fan to change.
      required: true
